version: '3'

networks:
  smart-monitor:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    privileged: true
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    ##restart: unless-stopped
    networks:
      smart-monitor:
          aliases:
                  - prometheus.smart-monitor.com  
    labels:
      org.label-schema.group: "monitoring"              
                  
                  
                  
  nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      smart-monitor:
          aliases:
                  - nodeexporter.smart-monitor.com
    labels:
      org.label-schema.group: "monitoring"              
    

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    #restart: unless-stopped
    networks:
      smart-monitor:
          aliases:
                  - cadvisor.smart-monitor.com
    labels:
      org.label-schema.group: "monitoring"
      

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    privileged: true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    #restart: unless-stopped
    networks:
      smart-monitor:
          aliases:
                  - grafana.smart-monitor.com      
    labels:
      org.label-schema.group: "monitoring"
  
  
  
  
  proxyserver:
    container_name: proxyserver
    build:
        context: ./nginx_revers_proxy/config/
        dockerfile: Dockerfile
    privileged: true
        #volumes:
        #    - ./certbot/certbot/conf:/etc/letsencrypt
         #   - ./certbot/certbot/www:/var/www/certbot      
    ports:
        - "80:80"
        - "443:443"
        - "42:22"
    networks:
        - smart-monitor
    tty: true
    labels:
      org.label-schema.group: "monitoring"

   
